#!/bin/bash

NAME=`basename $PWD`

time=$(date "+%Y-%m-%d %H:%M:%S")

dpthvHeader="
;TYPE=PLATED
;Layer: PTH_Through_Via
;EasyEDA Pro v2.2.32.3, ${time}
;Gerber Generator version 0.3
"

dpthHeader="
;TYPE=PLATED
;Layer: PTH_Through
;EasyEDA Pro v2.2.32.3, ${time}
;Gerber Generator version 0.3
"

function genGerber {
    echo "Generating ${1}"
    echo "
G04 Layer: ${1}*
G04 EasyEDA Pro v2.2.32.3, ${time}*
G04 Gerber Generator version 0.3*
G04 Scale: 100 percent, Rotated: No, Reflected: No*
G04 Dimensions in millimeters*
G04 Leading zeros omitted, absolute positions, 3 integers and 5 decimals*
" > Gerber_${1}.${2}
}

echo "KiCad2EasyEDA 2024 Jelly Terra"
echo

if [ -z $1 ]
then
    echo "ERROR: Inner layers is undefined!"
    echo
    echo "Usage: $0 (inner layers)"
    exit
fi

echo "Inner layers: ${1}"
echo

rm -rf output
mkdir output

cd output

genGerber TopLayer GTL
genGerber TopSolderMaskLayer GTS
genGerber BottomLayer GBL
genGerber BottomSolderMaskLayer GBS
genGerber TopSilkscreenLayer GTO
genGerber BottomSilkscreenLayer GBO
genGerber BoardOutlineLayer GKO

for N in $(seq 1 $1)
do
    genGerber InnerLayer${N} G${N}
    cat ../*In${N}_Cu* >> Gerber_InnerLayer${N}.G${N}
    if [ $? != 0 ]
    then
        echo "ERROR: Something went wrong. Make sure the inner layers setting is correct."
        exit
    fi
done

echo "Generating drill files"
echo $dpthHeader > Drill_PTH_Through.DRL
echo $dpthvHeader > Drill_PTH_Through_Via.DRL

cat ../*F_Cu* >> Gerber_TopLayer.GTL
cat ../*F_Mask* >> Gerber_TopSolderMaskLayer.GTS
cat ../*B_Cu* >> Gerber_BottomLayer.GBL
cat ../*B_Mask* >> Gerber_BottomSolderMaskLayer.GBS
cat ../*F_Silk* >> Gerber_TopSilkscreenLayer.GTO
cat ../*B_Silk* >> Gerber_BottomSilkscreenLayer.GBO

cat ../*Edge* >> Gerber_BoardOutlineLayer.GKO
cat ../*NPTH* >> Drill_PTH_Through.DRL
cat ../*-PTH* >> Drill_PTH_Through_Via.DRL

echo "Complete!"

zip $NAME.zip *
